### ISSUE TITLE
Error: Non-relative paths are not allowed when 'baseUrl'

### ISSUE THREAD

**Issue by homerjam** [esbuild-kit/esm-loader#26]
Hello!

I'm absolutely loving TSX, the dev experience is 💯 

I started getting this error recently, I believe it is since the recent support for paths in tsconfig.

```
Error: Non-relative paths are not allowed when 'baseUrl' is not set. Did you forget a leading './'?
    at file:///Users/jameshomer/Projects/Rosewood/node_modules/.pnpm/get-tsconfig@4.0.2/node_modules/get-tsconfig/dist/index.mjs:3:7227
    at Array.map (<anonymous>)
    at file:///Users/jameshomer/Projects/Rosewood/node_modules/.pnpm/get-tsconfig@4.0.2/node_modules/get-tsconfig/dist/index.mjs:3:7105
    at Array.map (<anonymous>)
    at se (file:///Users/jameshomer/Projects/Rosewood/node_modules/.pnpm/get-tsconfig@4.0.2/node_modules/get-tsconfig/dist/index.mjs:3:7002)
    at ce (file:///Users/jameshomer/Projects/Rosewood/node_modules/.pnpm/get-tsconfig@4.0.2/node_modules/get-tsconfig/dist/index.mjs:3:7533)
    at file:///Users/jameshomer/Projects/Rosewood/node_modules/.pnpm/@esbuild-kit+esm-loader@2.2.0/node_modules/@esbuild-kit/esm-loader/dist/index.js:1:338
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
```

Here is tsonfig.json
```json
{
  "extends": "./.svelte-kit/tsconfig.json",
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true
  }
}
```

And .svelte-kit/tsconfig.json
```json
{
	"compilerOptions": {
		"baseUrl": "..",
		"paths": {
			"$lib": [
				"src/lib"
			],
			"$lib/*": [
				"src/lib/*"
			]
		},
		"rootDirs": [
			"..",
			"./types"
		],
		"importsNotUsedAsValues": "error",
		"isolatedModules": true,
		"preserveValueImports": true,
		"lib": [
			"esnext",
			"DOM"
		],
		"moduleResolution": "node",
		"module": "esnext",
		"target": "esnext"
	},
	"include": [
		"../src/**/*.js",
		"../src/**/*.ts",
		"../src/**/*.svelte"
	],
	"exclude": [
		"../node_modules/**",
		"./**"
	]
}
```

I was able to fix the issue by manually adding `baseUrl` to my root tsconfig.json.

It seems like perhaps the extends feature is supported for `paths` but not `baseUrl`, maybe this is relevant to get-tsconfig?

Furthermore, after I added `baseUrl` which fixed this isuue I then had to add `.js` onto a couple of relative module paths - not a big deal but I thought this loader was supposed to support this automatically. ie. `lodash/orderBy` -> `lodash/orderBy.js`.

Thanks!

**Comment by homerjam** [comment]
Ah yes sorry, it's not relative 😅 but basically it was working without the `.js` in the path and then when I updated tsx it started complaining. I'll try and get a repro together.
