### ISSUE TITLE
Loading WASM is not supported

### ISSUE THREAD

**Issue by SettingDust** [esbuild-kit/esm-loader#48]
Seems like can't handle wasm I guess. Can I use esbuild plugin?

https://github.com/SettingDust/esm-loader-parse-error
There isn't `"type": "module"` in `@minify-html/wasm` package.json. So I added

```
Error: Parse error @:1:285
    at yt (E:\javascript\esm-loader-parse-error\node_modules\@esbuild-kit\core-utils\dist\index.js:9:7926)
    at oA (E:\javascript\esm-loader-parse-error\node_modules\@esbuild-kit\core-utils\dist\index.js:14:66)
    at dt (E:\javascript\esm-loader-parse-error\node_modules\@esbuild-kit\core-utils\dist\index.js:22:85)
    at H (file:///E:/javascript/esm-loader-parse-error/node_modules/@esbuild-kit/esm-loader/dist/index.js:1:2969)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:605:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11) {
  idx: 284
}

```
Full log: 
https://pastes.dev/t9RjNTub7P

**Comment by privatenumber** [comment]
In the latest release, esm-loader should properly ignore the `.wasm` extension and defer to Node.js.

In Node.js and `tsx`, you can enable WASM via `--experimental-wasm-modules`:

```sh
tsx --experimental-wasm-modules ./file.js
```

**Comment by SettingDust** [comment]
Can I load esbuild plugin? Want to include wasm as base64

**Comment by privatenumber** [comment]
Its Node.js so you can pass in a Node.js loader.

**Comment by SettingDust** [comment]
> Its Node.js so you can pass in a Node.js loader.

You means I need write a loader by myself?

**Comment by privatenumber** [comment]
Not necessarily but I suppose if you can't find one.

**Comment by SettingDust** [comment]
> Not necessarily but I suppose if you can't find one.

Okay, thanks a lot for your patience
